### ISSUE TITLE
error loading bug 

### ISSUE THREAD

**Issue by gKreator** [donejs/autorender#37]
I get allot of error loading issues using this branch. 

`0.9.0-pre.2`

![image](https://cloud.githubusercontent.com/assets/1431487/21284206/6c006a66-c3da-11e6-9e7b-cf7cbf457c5e.png)

This was on the BitBalls master branch

**Comment by frank-dspeed** [comment]
Confirmed happens with current bitballs master!

**Comment by matthewp** [comment]
I'll try it out.

**Comment by matthewp** [comment]
The problem is 0.9.0-pre.2 is not compatible with Steal 0.16 and bitballs uses Steal 0.16.  If someone wants to checkout the `major` branch and submit a PR that changes `steal` to `system` [here](https://github.com/donejs/autorender/blob/0cb03c2c48c06d1177e26086f1f86158f8e6dae6/package.json#L39) it will be compatible with both 0.16 and 1.0

**Comment by matthewp** [comment]
i'll do it.

**Comment by matthewp** [comment]
https://github.com/donejs/autorender/pull/38 will release when that passes.

**Comment by matthewp** [comment]
This is fixed in 0.9.0-pre.3

**Comment by gKreator** [comment]
Yup it works. Thanks!
